
## First convert the key to base64 format 
## echo "xa56rgyth" | base64 // this will encode to base64
## echo -n "c3VwZXJzZWNyZXQ=" | base64 --decode // this will decode to plain text


## Creating secret for the API keys

apiVersion: v1
data:
  apikey: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  name: my-secret



## We have 3 methods to use that created secret to pod 

## Method 1 - using environment variable
## Method 2 - using EnvFrom
## Method 3 - Using as volume mount




## Method 1 - using environment variable

apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_APIKEY
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: apikey
            
            
 
## Method 2 - using EnvFrom

apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
    - name: mycontainer
      image: nginx
      envFrom:
      - secretRef:
          name: my-secret
 
 
## Method 3 - Using as volume mount
 
apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
 
 
            
            
