
## First convert the key to base64 format 
## echo "xa56rgyth" | base64 // this will encode to base64
## echo -n "c3VwZXJzZWNyZXQ=" | base64 --decode // this will decode to plain text


## Creating secret for the API keys

apiVersion: v1
data:
  apikey: c3VwZXJzZWNyZXQ=
kind: Secret
metadata:
  name: my-secret



## We have 3 methods to use that created secret to pod 

## Method 1 - using environment variable
## Method 2 - using EnvFrom
## MEthod 3 - Using as volume mount
